version: '3.8'

services:
  whatsapp-service:
    build: ./backend
    container_name: pms-whatsapp
    ports:
      - "3001:3001"
    volumes:
      - ./backend/tokens:/usr/src/app/tokens
    restart: unless-stopped
